### ISSUE TITLE
Training failing(shape mismatch error) at calculating validation loss.

### ISSUE THREAD

**Issue by dupree** [Toni-Antonova/VAE-Text-Generation#2]
Hi Toni
Thank you for sharing this, I am trying to reuse this repository to encode my sentences. On training the model the test set runs well but as soon as it gets to calculating the validation loss the process fails with a shape mismatch error. It complains generally in this direction -
 `ValueError: Cannot feed value of shape (75, 3000) for Tensor u'input_15:0', which has shape '(500, 3000)'`

Where 3000 - is my max sentence len and 500 - is the batch size. However this number 75 is somehow generated dynamically and is different for different max-len and batch size values. Could you maybe give me a direction what might be going wrong here.
Thanks.

**Comment by ghost** [comment]
The training data being supplied should be multiple of batch_size i.e. 500 .. for remaining data in last batch it gives the error

**Comment by vmkhlv** [comment]
@dupree Hi, your train and test data should be in right proportions. E.g. with the batch size of 500 and the total number of examples of 5000, your train data should be of 4000 and test data of 1000. You need to cut the validation set by 75 examples.

**Comment by dupree** [comment]
Thanks for your input guys @vmkhlv  @SandeepBhutani . I am no longer working on this project but it's a good information that might be useful for community.
